### ISSUE TITLE
Tree view triangles pixelated

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#75]
In comparison to the Body and Box icon, the triangles for collapsing and expanding appear pixelated on a HiDPI screen on Windows.
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/2d636b39-9f9d-4e08-b00a-ff60328b0a4f)

**Comment by DrD4ffy** [comment]
But you have nice triangles. My look stretched like this:
![image](https://github.com/obelisk79/OpenDark/assets/156334536/7d66fb51-c8a8-4077-9b25-c4b8ecb9f5be)

**Comment by obelisk79** [comment]
I have addressed the issues with the triangles with a better implementation in the stylesheets. I'd like to push updates soon, but I've been pulled several directions with various projects/efforts and real life demands.

**Comment by maxwxyz** [comment]
Still present in OpenTheme, only the OpenDark version:
![image](https://github.com/obelisk79/OpenDark/assets/6246609/ca1351f4-2773-47a1-9487-0110c88b926b)


OpenLight has other icons and looks good:
![image](https://github.com/obelisk79/OpenDark/assets/6246609/043daa72-8ada-4526-8723-555e578e87a3)

**Comment by maxwxyz** [comment]
Same issue in the preferences. Dark version using mixed arrows, not always legible, Light uses better ones.
![image](https://github.com/obelisk79/OpenDark/assets/6246609/689775cc-8e17-40db-91f2-04b9b2c6d279)

![image](https://github.com/obelisk79/OpenDark/assets/6246609/01dfa4bd-3ed5-4ceb-8bdc-fbe7f9819af5)

**Comment by obelisk79** [comment]
Interesting, I'll try to fix this today. That's a notable issue
